### ISSUE TITLE
there should be "CONVERSATION-ID" instead of "CONVERSATION_ID", otherwise the conversationID will be null in ChatActivity

### ISSUE THREAD

**Issue by sbeliakova** [Nexmo/stitch-android-quickstart#16]
https://github.com/Nexmo/stitch-android-quickstart/blob/b16a210bac8fbbe66f54478942931df3b0dafdb8/examples/2-Inviting-members/app/src/main/java/com/nexmo/simpleconversation2/LoginActivity.java#L145

    private void goToConversation(final Conversation conversation) {
        Intent intent = new Intent(LoginActivity.this, ChatActivity.class);
        intent.putExtra("CONVERSATION-ID", conversation.getConversationId());
        startActivity(intent);
    }

**Comment by sbeliakova** [comment]
@ChrisGuzman please have a look to this

**Comment by ChrisGuzman** [comment]
Merged the PR. Thanks!
