### ISSUE TITLE
Let's use the new dependency com.nexmo.stitch instead of conversation

### ISSUE THREAD

**Issue by emmaChristine** [Nexmo/stitch-android-quickstart#17]
https://github.com/Nexmo/stitch-android-quickstart/blob/b16a210bac8fbbe66f54478942931df3b0dafdb8/examples/1-simple-conversation/app/build.gradle#L27

**Comment by ChrisGuzman** [comment]
Fixed in https://github.com/Nexmo/stitch-android-quickstart/commit/c4ef2559fc8b0229018e7878ec5f67a353169744
