### ISSUE TITLE
Cannot read property 'id' of null when I'm trying to add a member

### ISSUE THREAD

**Issue by Semeruk** [Nexmo/stitch-android-quickstart#21]
When I pass command to add a member to conversation into Terminal:

> nexmo member:add CON-e358b062-0c0a-4c0f-bf2f-ead355797783 action=join channel='{"type":"app"}' user_id=USR-53c906fe-759c-4775-8dd9-e91b7ccbc071

I receive this:

> /usr/local/lib/node_modules/nexmo-cli/lib/response.js:341
>       this.emitter.list('Member added: ' + response.id, response);
>                                                     ^
> 
> TypeError: Cannot read property 'id' of null
>     at Response.memberAdd (/usr/local/lib/node_modules/nexmo-cli/lib/response.js:341:53)
>     at HttpClient.__parseResponse (/usr/local/lib/node_modules/nexmo-cli/node_modules/nexmo/lib/HttpClient.js:187:9)
>     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/nexmo-cli/node_modules/nexmo/lib/HttpClient.js:110:19)
>     at IncomingMessage.emit (events.js:165:20)
>     at endReadableNT (_stream_readable.js:1101:12)
>     at process._tickCallback (internal/process/next_tick.js:152:19)

Can somebody help me with this?

**Comment by ChrisGuzman** [comment]
@Semeruk are you still experiencing this issue? If so please raise an issue on the nexmo CLI project: https://github.com/Nexmo/nexmo-cli/tree/beta

We've also released a new version of the CLI. Try updating the CLI to see if it works.
