### ISSUE TITLE
[Suggestion] Less confusing quotes in curl commands

### ISSUE THREAD

**Issue by alexfu** [Nexmo/stitch-android-quickstart#7]
This might just be me but, the curl commands in `1-simple-conversation` are slightly hard to read because of how the single quotes terminate right before an ENV variable. For example, in section 1.3:

```
curl -X POST https://api.nexmo.com/beta/conversations\
 -H 'Authorization: Bearer '$APP_JWT -H 'Content-Type:application/json' -d '{"name":"nexmo-chat", "display_name": "Nexmo Chat"}'
```

I think it would be much easier to read if it was written with only double quotes and the quotes didn't terminate before ENV variables...

```
curl -X POST https://api.nexmo.com/beta/conversations\
 -H "Authorization: Bearer $APP_JWT" -H "Content-Type:application/json" -d "{\"name\":\"nexmo-chat\", \"display_name\": \"Nexmo Chat\"}"
```

One slight disadvantage of my suggestion might be that the quotes in the body of the request will need to be escaped but I think that escaping quotes in a string is a standard that everyone understands.

**Comment by ChrisGuzman** [comment]
This was fixed by using CLI commands rather than cURL
